
var canvas = (function(canvas) {
	var drawing;
	var AllDays;  // Store all days data
	var Days;    // days to show 
	
	// 记录情绪指标的min max,
	var site_MIN_qx = 0;
	var site_MAX_qx = 0;
	var site_MIN_zs = 0;
	var site_MAX_zs = 0;
	var main_sz_title = Configure.title2.sz; // Configure.title2.qadq  or Configure.title2.sz

	var emotionPoints = [];   // 保存情绪的点
	var zbPoints = {};   // 保存其他指标的点

	var width = 0;
	var height = 0;
	var width_factor = 0.85;
	var height_factor = 0.8;
	var siteX;
	var siteY;
	var siteHeight;
	var siteWidth;
	var cellWidth = 0;
	//var cellHeight;
	var cell_factor = 0.92;
	var winFactor = Configure.WinFactor;

	var getDayFromDateStr = function(dateStr) {
		if (!AllDays || !AllDays.length ) {
			console.error('Days invalid');
		}
		return AllDays.find((d)=>{
			return Configure.formatExcelDate(d[Configure.title2.date], '') == dateStr;
		});
	};

	var autoGenerateDataFromExl = function(day) {
		var dateArr = workbook.getDateArr((a,b)=>{
				return b - a;
			});
		var dayIndex = dateArr.indexOf(Configure.formatExcelDate(day[Configure.title2.date], ''));
		var predayDate  = dateArr[dayIndex + 1];
		// 连扳数、晋级率   涨停数 跌停数 和炸板率
		if (!day[Configure.title2.erban] || !day[Configure.title2.boardnum]) {
			var param = {
				hotpointArr: [],
				type:-1,
				sort:1
			};
			var tickets =  parser.getTickets(dateArr[dayIndex], param);
			var dayNumberTitle = Configure.replaceTitleDate(Configure.title.dayNumber, dateArr[dayIndex]);
			var boardTimeTilte = Configure.replaceTitleDate(Configure.title.boardTime, dateArr[dayIndex]);
			day[Configure.title2.erban] = tickets.filter((t) => {
				return t[dayNumberTitle] == 2;
			}).length;
			day[Configure.title2.lianban] = tickets.filter((t) => {
				return t[dayNumberTitle] >= 2;
			}).length;
			tickets = tickets.sort((a, b)=>{
				return b[dayNumberTitle] - a[dayNumberTitle];
			})
			day[Configure.title2.height] = tickets[0][dayNumberTitle];
			if(predayDate) {
				preDay = getDayFromDateStr(predayDate);
				day[Configure.title2.jinji] = parseFloat((day[Configure.title2.lianban] -  day[Configure.title2.erban]) * 100/
												preDay[Configure.title2.lianban]).toFixed(2);
				if(!day[Configure.title2.zhangtingzhishu]) {
					preDay[Configure.title2.zhangtingzhishu] = preDay[Configure.title2.zhangtingzhishu] ? 
									preDay[Configure.title2.zhangtingzhishu] : 100;  // 如果表格中第一天没有初始化给一个初始值100
					day[Configure.title2.zhangtingzhishu] = parseInt(preDay[Configure.title2.zhangtingzhishu]) * 
															(100 + parseFloat(day[Configure.title2.boardR])) / 100;
				}
				if(!day[Configure.title2.lianbanzhishu]) {
					preDay[Configure.title2.lianbanzhishu] = preDay[Configure.title2.lianbanzhishu] ? 
									preDay[Configure.title2.lianbanzhishu] : 100;  // 如果表格中第一天没有初始化给一个初始值100
					day[Configure.title2.lianbanzhishu] = parseInt(preDay[Configure.title2.lianbanzhishu]) * 
															(100 + parseFloat(day[Configure.title2.boardsR])) / 100;
				}
			}
			// 涨停数、跌停数 炸板数 曾涨停数  亏钱效应
			day[Configure.title2.boardnum] = tickets.filter((t)=>{
				return t[dayNumberTitle] >= 1;
			}).length;
			day[Configure.title2.boardnum_20cm] = tickets.filter((t)=>{
				return t[dayNumberTitle] >= 1 && Configure.isKechuangTicket(t[Configure.title.code]);
			}).length;
			day[Configure.title2.floornum] = - tickets.filter((t)=>{
				return t[dayNumberTitle] == 0 && t[boardTimeTilte] == '--';
			}).length;
			day[Configure.title2.failednum] = - tickets.filter((t)=>{
				return t[dayNumberTitle] == 0 && t[boardTimeTilte] != '--';
			}).length;
			day[Configure.title2.boardednum] = Math.abs(day[Configure.title2.failednum]) + 
						day[Configure.title2.boardnum];
			day[Configure.title2.failedRate] = ((day[Configure.title2.failednum] + 
						day[Configure.title2.floornum]) / tickets.length).toFixed(2);
			if(!day[Configure.title2.failednum] || !day[Configure.title2.floornum] ||
					!day[Configure.title2.floored]){    // 兼容
				day[Configure.title2.floornum] = - rtDataManager.getHistoryRTticketsFloor(dateArr[dayIndex]).length;
				day[Configure.title2.boardednum] = rtDataManager.getHistoryRTticketsBoarded(dateArr[dayIndex]).length;
				day[Configure.title2.floored] = - rtDataManager.getHistoryRTticketsFloored(dateArr[dayIndex]).length;
				day[Configure.title2.failednum] = day[Configure.title2.boardnum] -
														day[Configure.title2.boardednum];
				day[Configure.title2.failedRate] = ((day[Configure.title2.failednum] + 
						day[Configure.title2.floornum]) / (day[Configure.title2.boardednum] - 
							day[Configure.title2.floored])).toFixed(2);
			}
			// 超跌数 领涨数
			if(!day[Configure.title2.jumped] || !day[Configure.title2.leader] ) {
				day[Configure.title2.jumped]  = - rtDataManager.getHistoryRTticketsJumped(dateArr[dayIndex]).length;
				day[Configure.title2.leader]  = rtDataManager.getHistoryRTticketsLeader(dateArr[dayIndex]).length;
			}
			
			// 资金总量  涨停的总    ###和-跌停的总和###
			day[Configure.title2.totalFund] = 0;
			tickets.forEach((ticket)=>{
				var fund = ticket[Configure.title.realHandoverPercent] * ticket[Configure.title.realValue] / 100 ?
							ticket[Configure.title.realHandoverPercent] * ticket[Configure.title.realValue] / 100 : 0;
				if(ticket[dayNumberTitle] >= 1) {
					day[Configure.title2.totalFund] += fund;
				} /*else if(ticket[dayNumberTitle] == 0 && ticket[boardTimeTilte] == '--') {
					day[Configure.title2.totalFund] -= fund;
				}*/
			});
			day[Configure.title2.totalFund] = (day[Configure.title2.totalFund] / 100000000).toFixed(2);   // 亿为单位
		}
		
		var calMa5AndBeili = function( ZHISHU_TITLE ,MA5Title,BEILItitle) {
			if(!day[MA5Title]) {
				var sum = parseInt(day[ZHISHU_TITLE]);
				// 当天和过去4天的和
				for(var i = 0; i < 4; i ++) {
					if (dateArr[dayIndex + i + 1]) {
						sum += parseInt(getDayFromDateStr(dateArr[dayIndex + i + 1])[ZHISHU_TITLE]);
					}
				}
				day[MA5Title] = parseInt(sum/5);
				day[BEILItitle] = parseFloat((day[ZHISHU_TITLE] - day[MA5Title]) * 100/
												day[ZHISHU_TITLE]).toFixed(2);
			}
		}
		
		if(Configure.ZHISHU_TITLE == Configure.title2.qingxuzhishu ) {
			// 涨停板 ma5和背离率
			calMa5AndBeili(Configure.title2.zhangtingzhishu, Configure.title2.ma5, Configure.title2.beili);
			// 连扳 MA5 和 背离率
			calMa5AndBeili(Configure.title2.lianbanzhishu, Configure.title2.subMa5, Configure.title2.subBeili);
		} else {
			calMa5AndBeili(Configure.ZHISHU_TITLE, Configure.title2.ma5, Configure.title2.beili);
			calMa5AndBeili(Configure.ZHISHU_SUB_TITLE, Configure.title2.subMa5, Configure.title2.subBeili);
		}

		return day;
	};
	
	var resize = function(c, winXfactor) {
		var ctx = c.getContext("2d");
		ctx.clearRect(0, 0, width, height);

		width = c.width * winXfactor;
		height = c.height;

		siteX = width * (1 - width_factor)/2;
		siteY = height * (1 - height_factor)/2;
		siteWidth = width * width_factor;
		siteHeight = height * height_factor;
		Configure.Debug('canvas width:' + width + 
					' height:' + height + 
					' siteX' + siteX +
					' siteY:' + siteY +
					' siteWidth:' + siteWidth + 
					' siteHeight:' + siteHeight);
	};
	
	var reload = function() {	
		AllDays = workbook.getDatesSheet();			
		// 通过parser分析出当天的echelon
		AllDays.forEach((d)=>{
			var dateStr = Configure.formatExcelDate(d[Configure.title2.date], '');
			if (workbook.sheetExist(dateStr)) {
				autoGenerateDataFromExl(d);
				// Echelons
				d[Configure.title2.echelons] = parser.getEchelons(dateStr);
				// boardHeight
				var objBH = parser.getBoardHeight(dateStr, Configure.title2.BH_Draw_title );
				if (objBH) {
					d[Configure.title2.boardHeight] = objBH.value;
					d[Configure.title2.dragon] = objBH.name;
				}
			} else {
				d[Configure.title2.echelons] = [];
				d[Configure.title2.boardHeight] = 0;
				d[Configure.title2.dragon] = '';
			}
		});
	}

	var init = function(c, winXfactor = 1) {
		drawing = c;
		resize(c, winXfactor);
		reload();
	};

	var drawSite = function(indecatorName, echelonNames) {
		//画线
		var ctx = drawing.getContext("2d");		
		ctx.beginPath();
		ctx.lineWidth="2";
		ctx.strokeStyle = Configure.site_color;
	//	ctx.moveTo(siteX,siteY);
		ctx.moveTo(siteX ,siteY + siteHeight);
		ctx.lineTo(siteX + siteWidth, siteY + siteHeight);
		ctx.lineTo(siteX + siteWidth, siteY);
		ctx.lineTo(siteX,siteY);
		
		var Toffset = -1;
		
		// 画日期
		for(i = 0; i < Days.length; i ++) {
			// 日期网格
			/*var d = new Date(Configure.formatExcelDate(Days[i][Configure.title2.date], '/'));
			if (d.getDay () == 1) {   // 星期一
				ctx.font="14px 楷体";
				ctx.fillStyle = Configure.site_color;
				ctx.fillText(Configure.formatExcelDate(Days[i][Configure.title2.date], '').substr(4,4),
					 siteX + cellWidth  * i, siteY + siteHeight + 20);
					 
				ctx.lineWidth="0.5";
				ctx.strokeStyle = Configure.site_color;
				ctx.moveTo(siteX + cellWidth  * i,siteY);
				ctx.lineTo(siteX + cellWidth  * i,siteY + siteHeight);
			}*/
			//画大周期
			var cycle = workbook.getEmotionalCycles(Configure.formatExcelDate(Days[i][Configure.title2.date]));
			if (cycle && !!cycle.cycles && cycle.isTurning) {
				ctx.font= cycle.cycles.includes('T') || cycle.cycles.includes('t') ? "16px 楷体 bold" :
													"12px 楷体 bold";
				ctx.fillStyle = cycle.cycles.includes('M') ? 'red' : 
					cycle.cycles.includes('Q') ? 'blue' :
					cycle.cycles.includes('T') || cycle.cycles.includes('t') ? 'red' :
					cycle.cycles.includes('m') || cycle.cycles.includes('q') ? 'green' :
					cycle.cycles.includes('H') || cycle.cycles.includes('P') ? 'black' :
					cycle.cycles.includes('s') || cycle.cycles.includes('S') ? 'grey' : Configure.site_color;
				// 宏观周期阶段
				if (/[TtQqMmHP]/.test(cycle.cycles)) {
					ctx.fillText(/[Ww]/.test(cycle.cycles) ? 
									cycle.cycles.substring(0, cycle.cycles.indexOf('w')) : cycle.cycles, 
									siteX + cellWidth  * i, siteY -5);
					if (!!cycle.hotpoint) {
						ctx.font="12px 楷体";
						ctx.fillStyle = 'orange';
						ctx.fillText(cycle.hotpoint, siteX + cellWidth  * i + 20, siteY -5);
					}
					if (new RegExp(`[${Configure.TpiontShow}]`).test(cycle.cycles)) {
						Toffset = i;  // 记录锚点位置
					}
				} else if (Toffset < i && Toffset != -1 &&    //box上面的数字
								JSON.parse(Configure.emotionProgress.trim()).includes(i-Toffset)) { 
					ctx.font="12px 楷体";
					ctx.fillStyle = 'red';
					ctx.fillText('+' + (i - Toffset), siteX + cellWidth  * i, siteY -5);
				}
				
				// 周期网格
				if (new RegExp(`[${Configure.TpiontLine}]`).test(cycle.cycles)) {
						ctx.font="14px 楷体";
						ctx.fillStyle = Configure.site_color;
						ctx.fillText(Configure.formatExcelDate(Days[i][Configure.title2.date], '').substr(4,4),
							 siteX + cellWidth  * i, siteY + siteHeight + 20);
					 
						ctx.lineWidth="0.5";
						ctx.strokeStyle = Configure.site_color;
						ctx.moveTo(siteX + cellWidth  * i,siteY);
						ctx.lineTo(siteX + cellWidth  * i,siteY + siteHeight);
				}
				if(Configure.getColorFromWinC(cycle.cycles).color){   // 微观情绪
					ctx.fillStyle = Configure.getColorFromWinC(cycle.cycles).color;
					ctx.fillRect(siteX + cellWidth  * i, siteY + siteHeight*(1- winFactor) + 1, cellWidth, 5);
				}
			}
		};		
		
		// 画0轴
		ctx.lineWidth="0.5";
		ctx.strokeStyle = Configure.site_color;
		ctx.moveTo(siteX,siteY + siteHeight * (1-winFactor));
		ctx.lineTo(siteX + siteWidth,siteY + siteHeight * (1-winFactor));	
		// 画内部网格
		/*for(var i = 1; i <= 3; i ++) {
			if (i != 2) {
				ctx.moveTo(siteX,siteY + siteHeight * (1-winFactor)*i/4);
				ctx.lineTo(siteX + siteWidth,siteY + siteHeight * (1-winFactor)*i/4);
			}
		}  */
		///
		if (!echelonNames.length ) {
			ctx.fillStyle = Configure.line_color;
			if (Configure.ZHISHU_TITLE == Configure.title2.qingxuzhishu) {
				ctx.fillText(site_MIN_qx, siteX + siteWidth - 10, siteY + siteHeight * (1- winFactor) + 10);
				ctx.fillText(site_MAX_qx, siteX + siteWidth - 16, siteY + 12);
			} else {
				ctx.fillText(Configure.MIN_BEILI, siteX + siteWidth - 10, siteY + siteHeight * (1- winFactor)+ 10);
				ctx.fillText(Configure.MAX_BEILI + '%', siteX + siteWidth - 16, siteY + 12);
			}
		} 
		ctx.stroke(); 
	};

	var drawEmotionTurning = function() { 
		var ctx = drawing.getContext("2d");		
		ctx.beginPath();
		// 标记转点
		emotionPoints.forEach((p)=> {
			if(p.angleA5  && !p.isOnlyDisplay) {
				ctx.fillStyle = p.angleA5 > 0 ?  'green' : 'red';
				ctx.fillRect(p.point.x - 4, p.point.y -4, 8, 8);
				ctx.font="bold 14px 楷体";
				ctx.fillText(p.angleA5.toFixed(1), p.point.x, p.point.y);
			} else if(p.isOnlyDisplay) {
				ctx.font="12px 楷体";
				ctx.fillText('(' + p.angleA5.toFixed(1) + ')', p.point.x, p.point.y + 14);
			}
			ctx.stroke();
		});
	};
	var drawEmotionCycle = function(curEmotion) { 
		var ctx = drawing.getContext("2d");		
		var center = Math.ceil(Configure.winCtxts.length/2);
		for(var i = 0; i < Configure.winCtxts.length; i ++) {
			var xLv = i-center < 0 ? 0 : 1;
			var yLv = i-center >= 0 ?  Math.abs(i-center) + 0.5 :  Math.abs(i-center);
		//	Configure.Debug('x = ' + xLv + '  y = ' + yLv);
			var x = siteX + siteWidth + 15 * xLv;
			var y = siteY + 5 + 30 * yLv;
			var txt = '';
			if(Configure.winCtxts[i] == curEmotion) {
				ctx.beginPath();
				ctx.font="bold 16px 楷体";
				ctx.fillStyle = Configure.getColorFromWinC('w' + i).color;
				txt = curEmotion + (xLv == 0 ? ' <' : '<');
			} else {
				ctx.beginPath();
				ctx.font="bold 12px 楷体";
				ctx.fillStyle = Configure.getColorFromWinC('w' + i).color;
				txt = Configure.winCtxts[i];
			}
			ctx.fillText(txt, x, y);
			ctx.stroke();
		}
	};
	var drawIndicators = function(indecatorName, echelonNames) {
		var ctx = drawing.getContext("2d");		
		ctx.beginPath();
		// 情绪维度1 -- 资金热度
		function drawBottom(title, maxOffset) {
			var rectHeight = Days[i][title] ? 
						siteHeight * winFactor * parseFloat(Days[i][title]) /maxOffset : 0;
			var rect = {x: siteX + cellWidth  * i,
						y: siteY + siteHeight - rectHeight,
						width: cellWidth*0.9,
						height: rectHeight};
			var grd=ctx.createLinearGradient(rect.x, rect.y + + siteHeight * winFactor * 0.5, 
											rect.x, rect.y);
			if(parseFloat(Days[i][title]) < maxOffset/5) {
				grd.addColorStop(0,"yellow");
				grd.addColorStop(1,"green");
			} else {
				grd.addColorStop(0,"orange");
				grd.addColorStop(1,"red");
			} 
			ctx.fillStyle=grd;
			ctx.fillRect(rect.x, rect.y, rect.width, rect.height);
			if (i == Days.length - 1) {
				ctx.font="14px 楷体";
				ctx.fillText(parseFloat(Days[i][title]), rect.x + 5, rect.y - 10);
			}
			ctx.font="14px 楷体";
			ctx.fillStyle = Configure.line_color;
			ctx.fillText('0', siteX - 20, siteY + siteHeight + 10);
			ctx.fillText(maxOffset, siteX - 30, siteY + siteHeight * (1- winFactor) + 10);
			ctx.stroke();
		};
		// head 情绪维度2 -- 市场恐慌     foot 情绪维度3 -- 风险偏好
		function drawHeadorFoot(color, zero, maxOffset, title, indecatorIndex, isHead = true) {
			ctx.beginPath();
			ctx.fillStyle= color;
			ctx.strokeStyle = color;
			var vReverseHeight = isHead ? 0 : siteHeight*(1-winFactor);
			var pointH = siteHeight * (1-winFactor) * 
				(parseFloat(Math.abs(Days[i][title]))- zero)/maxOffset;
			var pointY = siteY + vReverseHeight + ( isHead ? pointH : - pointH)
			var point = {x: siteX + cellWidth  * i + indecatorIndex * 0.33 * cellWidth, y: pointY};
		//	ctx.fillRect(point.x, point.y, 2, 2);
			ctx.lineWidth=cellWidth/2.5;
			ctx.moveTo(point.x, siteY + vReverseHeight);
			ctx.lineTo(point.x, point.y);
			ctx.stroke();
		};
		
		// 情绪维度4 -- 赚钱效益
		function drawUpon(zero, max, title) {
			ctx.beginPath();
			ctx.fillStyle="black";
			ctx.strokeStyle = "black";
			var pointH = siteHeight * (1-winFactor) * (parseFloat(Days[i][title]) - zero)/(max - zero);
			var point = {x :siteX + cellWidth  * i + 0.5 * cellWidth,
						y: siteY + siteHeight*(1-winFactor) - pointH};	
							
			emotionPoints.push({point:point, value:parseFloat(Days[i][title]), 
						date:Days[i][Configure.title2.date]});
							
			grd=ctx.createLinearGradient(siteX, siteY + siteHeight * (1-winFactor), 
												siteX, siteY);
			grd.addColorStop(0,"green");
			grd.addColorStop(0.3,"orange");
			grd.addColorStop(1,Configure.line_color);  
			ctx.fillStyle = grd;
			ctx.strokeStyle = grd;
			if (i < Days.length - 1) {// 不是最后一个点
				var pointNextH = siteHeight * (1-winFactor) * (parseFloat(Days[i + 1][title]) - zero)/(max - zero);
				var pointNext = {x:siteX + cellWidth  * (i + 1) + 0.5 * cellWidth,
								y: siteY + siteHeight*(1-winFactor) - pointNextH};
				ctx.lineWidth="4";
				ctx.moveTo(point.x, point.y);
				ctx.lineTo(pointNext.x, pointNext.y);
				ctx.stroke();
			} else {
				ctx.font="14px 楷体";
				ctx.fillText(parseFloat(Days[i][title]), point.x + 10, point.y);
				ctx.stroke();
			}
		}
		
		// 情绪维度5 -- 指数维度
		function drawLine(color, zero, maxOffset, title, draw = true) {
			var ctx = drawing.getContext("2d");		
			ctx.beginPath();
			ctx.fillStyle= color;
			var pointH = siteHeight * (1-winFactor) * 
				(parseFloat(Days[i][title])- zero)/maxOffset;
			var szPoint = {x: siteX + cellWidth  * i + 0.5 * cellWidth,
					y: siteY + siteHeight*(1-winFactor) - pointH};
			//	ctx.fillRect(szPoint.x, szPoint.y, 2, 2);
			if (echelonNames.length <= 1 && draw) {
				if (i < Days.length - 1) {// 不是最后一个点
					var pointNextH = siteHeight * (1-winFactor) * 
						(parseFloat(Days[i + 1][title]) - zero)/maxOffset;
					var szpointNext = {x:siteX + cellWidth  * (i + 1) + 0.5 * cellWidth,
									y: siteY + siteHeight*(1-winFactor) - pointNextH};
					// 画阈值线
					ctx.lineWidth="3";
					ctx.strokeStyle = 'black';
					ctx.moveTo(szPoint.x,siteY + siteHeight * (1-winFactor)/2);
					ctx.lineTo(szpointNext.x - 10,siteY + siteHeight * (1-winFactor)/2);
					ctx.stroke();
					// 画数据线
					ctx.lineWidth="2";
					ctx.strokeStyle = color;
					ctx.moveTo(szPoint.x, szPoint.y);
					ctx.lineTo(szpointNext.x, szpointNext.y);
					ctx.stroke();
				} else {
					ctx.font="14px 楷体"
					ctx.fillText(parseFloat(Days[i][title]) + '', szPoint.x, szPoint.y);
					ctx.stroke();
					// 写坐标值
					if(title != Configure.title2.boardedR &&
						title != Configure.title2.boardR ) {  // 昨日涨停收益 不写
						ctx.fillText(zero, siteX - 30, siteY + siteHeight * (1- winFactor));
						ctx.fillText(zero + maxOffset, siteX - 30, siteY);
						ctx.stroke();
					}

				}
			}
			if (!zbPoints[title]) {
				zbPoints[title] = [];
			}
			zbPoints[title].push({point:szPoint, value:parseFloat(Days[i][title]),
									 date:Days[i][Configure.title2.date]});		
			return szPoint;
		};
		
		for(i = 0; i < Days.length; i ++) {
			ctx.beginPath();
			if (echelonNames.length == 0) {   // 没有echolon显示底部量能就显示总量能
				Configure.ZHISHU_TITLE == Configure.title2.lianbanzhishu ? 
					drawBottom(Configure.title2.jinji, 100) : drawBottom(Configure.title2.totalFund, Configure.Fund_MaxOffset);
			} 
			if (echelonNames.length <= 1) {
				drawHeadorFoot('rgba(0,158,0,0.4)', 0, 2000, Configure.title2.jumped, 1, true);
				drawHeadorFoot('rgba(0,50,0,0.4)', 0, 200, Configure.title2.floored, 2, true);
				drawHeadorFoot('rgba(128,0,0,0.4)', 0, 200,  Configure.title2.lianban, 3,false);
				drawHeadorFoot('rgba(255,0,0,0.4)', 0, 300,  Configure.title2.boardnum, 2,false);
				drawHeadorFoot('rgba(255,140,0,0.4)', 0, 500,  Configure.title2.boardednum, 1,false);
				
				Configure.ZHISHU_TITLE == Configure.title2.qingxuzhishu ? 
					drawUpon(site_MIN_qx, site_MAX_qx, Configure.title2.qingxuzhishu) :
					drawUpon(Configure.MIN_BEILI, Configure.MAX_BEILI, Configure.title2.beili);
			}		
			
			// 1 指数维度
			drawLine(Configure.sz_color, site_MIN_zs, site_MAX_zs - site_MIN_zs, 
								Configure.title2.sz ,indecatorName == '上证指数');	
			drawLine(Configure.sz_color, site_MIN_zs, site_MAX_zs - site_MIN_zs, 
							Configure.title2.qadq , indecatorName == '全A等权');	
		//	drawLine('black', 0, Configure.LEAER_NUM_MaxOffset, Configure.title2.leader, '上证指数' == indecatorName);  
			
			// 2 风险偏好
			drawLine('rgba(75,0,130,0.5)', -4, 16, Configure.title2.subBeili, indecatorName == '涨停背离'/*'连扳背离'*/); 
			drawLine('blue', -4, 16, Configure.title2.beili, indecatorName == '涨停背离');   

			// 3 资金热度    和短线资金配合
			drawLine('rgba(75,0,130,0.5)', -20, 50, Configure.title2.lianban, /*'连扳数量'*/'涨停数量' == indecatorName);  
			drawLine('red', 0, 300, Configure.title2.boardnum, '涨停数量' == indecatorName);          
			//drawLine('steelBlue', 5, 10, Configure.title2.boardnum_20cm, '涨停数量' == indecatorName);   
			 
			
			// 4 赚钱效益
			drawLine('rgba(128,0,0,1)', -6, 16, Configure.title2.boardsR, '赚钱效应' == indecatorName);
			drawLine('rgba(255,0,0,1)', -6, 16, Configure.title2.boardR, /*'涨停收益'*/ '赚钱效应' == indecatorName);
			drawLine('orange', -6, 16, Configure.title2.boardedR, '赚钱效应' == indecatorName);
			
			// 5 恐慌指数
			drawLine('green', -1, 1, Configure.title2.failedRate, '亏钱效应' == indecatorName);
			//drawLine('#20B2AA',  -20, 20, Configure.title2.failednum, /*'炸板数量'*/'亏钱效应' == indecatorName);
			//drawLine('#20B2AA', -2000, 2000, Configure.title2.jumped, /*'超跌数量'*/'亏钱效应' == indecatorName);
			drawLine('green', -200, 200, Configure.title2.floornum, /*'跌停数量'*/ '亏钱效应'== indecatorName);
						
			drawLine('blue', 0, 100, Configure.title2.jinji, '连扳晋级' == indecatorName);
			drawLine('blue', 100, 400, Configure.title2.totalFund, '短线资金' == indecatorName);
			drawLine('blue', 900, 100, Configure.title2.qingxuzhishu, '情绪指数' == indecatorName );
			
			//画连扳高度
			var point = drawLine('rgba(0,0,0,0.1)', Configure.BH_zero,
					Configure.BH_MaxOffset, Configure.BH_Draw_title, /*'连扳高度' == indecatorName*/ true);
			if (/*'连扳高度' == indecatorName &&*/
				i < Days.length - 1 && i > 0 && Days[i][Configure.title2.dragon] &&
				parseInt(Days[i][Configure.BH_Draw_title]) >= parseInt(Days[i+1][Configure.BH_Draw_title]) &&
					parseInt(Days[i][Configure.BH_Draw_title]) > parseInt(Days[i-1][Configure.BH_Draw_title])) {    // 只写最高点的名字
				ctx.fillStyle= 'rgba(0,0,0,0.8)';
				ctx.fillText(Days[i][Configure.title2.dragon].substr(0,2) + Days[i][Configure.BH_Draw_title]
							, point.x - 10, point.y - 5 < siteY ? siteY : point.y - 5);
				ctx.stroke();
			}
			////连扳高度
		};
		ctx.stroke();
	};
	
	var drawZTEchelon = function(echelonNames) {
		var ctx = drawing.getContext("2d");		
		function calPointHeight(g) {
			if(g && g[Configure.Echelons_show_type]) {
				return Configure.Echelons_show_type == 'score' ? 
				siteHeight * (1-winFactor) * parseFloat(g[Configure.Echelons_show_type] - Configure.Min_echelon_score)
						/ Configure.Max_echelon_score  : 
				siteHeight * (1-winFactor) * parseFloat(g[Configure.Echelons_show_type] - Configure.Min_echelon_fund)
						/ Configure.Max_echelon_fund;
			} else {
				return 0;
			}
		}
		
		function drawBottom(bund, maxOffset) {
			var rectHeight = bund ? 
						siteHeight * winFactor * parseFloat(bund) /maxOffset : 0;
			var rect = {x: siteX + cellWidth  * i,
						y: siteY + siteHeight - rectHeight,
						width: cellWidth*0.9,
						height: rectHeight};
			var grd=ctx.createLinearGradient(rect.x, rect.y + + siteHeight * winFactor * 0.5, 
											rect.x, rect.y);
			if(parseFloat(bund) < maxOffset/3) {
				grd.addColorStop(0,"yellow");
				grd.addColorStop(1,"green");
			} else {
				grd.addColorStop(0,"orange");
				grd.addColorStop(1,"red");
			} 
			ctx.fillStyle=grd;
			ctx.fillRect(rect.x, rect.y, rect.width, rect.height);
			if (i == Days.length - 1) {
				ctx.font="14px 楷体";
				ctx.fillText(parseFloat(bund), rect.x + 5, rect.y - 10);
			}
			ctx.font="14px 楷体";
			ctx.fillStyle = Configure.line_color;
			ctx.fillText('0', siteX - 20, siteY + siteHeight + 10);
			ctx.fillText(maxOffset, siteX - 30, siteY + siteHeight * (1- winFactor) + 10);
			ctx.stroke();
		}
		
		//site
		ctx.fillStyle = Configure.echelon_color[0];
		if (Configure.Echelons_show_type == 'score') {
			ctx.fillText(Configure.Min_echelon_score, siteX + siteWidth + 6, siteY + siteHeight * (1- winFactor));
			ctx.fillText(Configure.Max_echelon_score, siteX + siteWidth, siteY);
		} else {
			ctx.fillText(Configure.Min_echelon_fund, siteX + siteWidth + 6, siteY + siteHeight * (1- winFactor));
			ctx.fillText(Configure.Max_echelon_fund, siteX + siteWidth, siteY);
		}
		// 
		var bottomData = 0;
		for(i = 0; i < Days.length; i ++) {
			echelonNames.forEach((gName)=> {
				var echelonArr = Days[i][Configure.title2.echelons];
				var g = echelonArr.find((g)=>{   //  g : {name:'', hotPoints:[], score:'', fund:''};
					return g.name == gName;
				});
				var drawNameDone = false;	
				var pointH =  calPointHeight(g);
				// 记录底部数据
				if(g && g.fund) {
					bottomData = Configure.Echelons_show_type == 'score' ? g.fund : g.score;
				}
				/////
				var point = {x :siteX + cellWidth  * i + 0.5 * cellWidth,
						y: siteY + siteHeight*(1-winFactor) - pointH};	
							
				var color = Configure.echelon_color[echelonNames.indexOf(gName)%Configure.echelon_color.length];
								
				if (i < Days.length - 1) {   // 不是最后一天
					var echelonsNext = Days[i+1][Configure.title2.echelons];
					var gNext = echelonsNext.find((gN)=>{
						return gN.name == gName;
					});
					var pointNextH = calPointHeight(gNext);
					var pointNext = {x:siteX + cellWidth  * (i + 1) + 0.5 * cellWidth,
													y: siteY + siteHeight*(1-winFactor) - pointNextH};
					ctx.beginPath();
					ctx.lineWidth="3";
					ctx.strokeStyle = color;
					ctx.moveTo(point.x, point.y);
					ctx.lineTo(pointNext.x, pointNext.y);
					ctx.stroke();
					drawNameDone = true;
				}
				if (!drawNameDone && i == Days.length - 1) {  // 没有连线，画名称
					drawNameDone = true;
					ctx.beginPath();
					ctx.fillStyle= color;
					ctx.font="14px 楷体";
					ctx.fillText(g.name + g[Configure.Echelons_show_type] , point.x + 5, point.y);
					ctx.stroke();
				};
			});
			if (bottomData != 0 && bottomData != 'NaN') {
				drawBottom(bottomData, 200);
			}
		};
	};
	
	var drawBandEchelon = function(echelonNames) {
		var ctx = drawing.getContext("2d");		
		function calPointHeight(g) {
			return siteHeight * (1-winFactor) * parseFloat(g.score - Configure.RT_GAI_show_weight_min)
						/ (Configure.RT_GAI_show_weight_maxOffset + Configure.RT_GAI_show_weight_min);
		}
		
		// site
		ctx.fillStyle = Configure.echelon_color[0];
		ctx.fillText(Configure.RT_GAI_show_weight_min, siteX + siteWidth + 6, siteY + siteHeight * (1- winFactor));
		ctx.fillText(Configure.RT_GAI_show_weight_maxOffset + Configure.RT_GAI_show_weight_min
				, siteX + siteWidth, siteY);
		//
		for(i = 0; i < Days.length; i ++) {
			var echelonArr = parserRT.getRTEchelons();
			var dateStr = Configure.formatExcelDate(Days[i][Configure.title2.date], '');
			echelonArr.forEach((g)=> {    //  g : {name:'', hotPoints:[], score:'', fund:''};
				if(echelonNames.indexOf(g.name) != -1) {
					var drawNameDone = false;	
					var gHistory = parserRT.getHistoryEchelonFromDateStr(g, dateStr);
					var pointH =  calPointHeight(gHistory);
					var point = {x :siteX + cellWidth  * i + 0.5 * cellWidth,
							y: siteY + siteHeight*(1-winFactor) - pointH};	
							
					var color = Configure.echelon_color[echelonNames.indexOf(g.name)%Configure.echelon_color.length];
								
					if (i < Days.length - 1) {   // 不是最后一天
						var echelonsNext = Days[i+1][Configure.title2.echelons];
						var nextDateStr = Configure.formatExcelDate(Days[i+1][Configure.title2.date], '');
						var pointNextH = calPointHeight(parserRT.getHistoryEchelonFromDateStr(g, nextDateStr));
						var pointNext = {x:siteX + cellWidth  * (i + 1) + 0.5 * cellWidth,
													y: siteY + siteHeight*(1-winFactor) - pointNextH};
						ctx.beginPath();
						ctx.lineWidth="3";
						ctx.strokeStyle = color;
						ctx.moveTo(point.x, point.y);
						ctx.lineTo(pointNext.x, pointNext.y);
						ctx.stroke();
						drawNameDone = true;
					}
					if (!drawNameDone && i == Days.length - 1) {  // 没有连线，画名称
						drawNameDone = true;
						ctx.beginPath();
						ctx.fillStyle= color;
						ctx.font="14px 楷体";
						ctx.fillText(gHistory.name + gHistory.score , point.x - 25, point.y);
						ctx.stroke();
					};
				}
			});
		};
	};

	var getLastEmotionPoints = function(num) {
		var n = num > emotionPoints.length ? emotionPoints.length : num;
		var retP = [];
		for(var i = emotionPoints.length - 1; i > emotionPoints.length - 1 - n; i --) {
			retP.push(emotionPoints[i]);
		}
		return retP;
	};
	
	var getLastZBPoints = function(num, indecatorName = Configure.title2.sz) {
		var pArray = zbPoints[indecatorName] ? zbPoints[indecatorName] : [];
		var n = num > pArray.length ? pArray.length : num;
		var retP = [];
		for(var i = pArray.length - 1; i > pArray.length - 1 - n; i --) {
			retP.push(pArray[i]);
		}
		return retP;
	};
	
	/*
	* param pArray: [{point: {x: 714.4060000000001, y: 89.64}, value: 3258, date: '44984'}]
	*/
	var sumAngleFromPoints = function(pArray) {  
		var sumAngle = 0;
		for(var i = 0; i < pArray.length - 1; i ++){
			sumAngle += Configure.getAngle(pArray[i].point, pArray[i+1].point);
		}
		return sumAngle;
	}
	var sumValueFromPoints = function(pArray) {  
		var sumValue = 0;
		for(var i = 0; i < pArray.length - 1; i ++){
			sumValue +=  pArray[i].value;    
		}
		return sumValue;
	}
	
	var findTurnintPoint = function(pArray, maNum) {
		var tmpTrend = 0;   // 趋势 >0向上  <0向下
		for(var i = 0; i < pArray.length-maNum; i ++){
			var pointArr = pArray.slice(i, i + maNum);
			var averageSum = sumAngleFromPoints(pointArr)/(maNum-1);
			if(tmpTrend * averageSum < 0 && Math.abs(averageSum) > 10) {  // 转点
				pArray[i].angleA5 = averageSum;     // pArray 是从最近一个点往前
				tmpTrend = averageSum;
			} else if (tmpTrend == 0) {
				tmpTrend = averageSum;
			}
			//最近一个点记录数据
			if(i == 0) {
				pArray[i].angleA5 = averageSum;
				pArray[i].isOnlyDisplay = true;
			}
		}
	};
	
	var clear = function() {
		emotionPoints = [];   // 保存背离率的点
		zbPoints = {};   // 保存其他指标的点
		site_MIN_qx = 0;
		site_MAX_qx = 0;
		site_MIN_zs = 0;
		site_MAX_zs = 0;
	};
	var draw = function(echelonNames, indecatorName, showDaysNumber) {
		if (drawing.getContext){
			window.performance.mark("Canvas:draw");
			var ctx = drawing.getContext("2d");
			ctx.clearRect(0, 0, width, height);
			clear();
			
			//cut Days to display
			var maxShowLengh = AllDays.length - Configure.Days_Show_reserved_lengh;
			showDaysNumber = showDaysNumber > maxShowLengh ? maxShowLengh : showDaysNumber;
			
			Days = AllDays.slice(AllDays.length - showDaysNumber, AllDays.length);
			cellWidth = siteWidth / showDaysNumber *cell_factor;  
			Days.forEach((d)=>{      // 提前获取坐标
				var base = 50;
				if(!site_MIN_qx || d[Configure.title2.qingxuzhishu] < site_MIN_qx ) {
					site_MIN_qx = Math.floor(d[Configure.title2.qingxuzhishu] / base) * base;
				} else if(!site_MAX_qx || d[Configure.title2.qingxuzhishu] > site_MAX_qx){
					site_MAX_qx = Math.ceil(d[Configure.title2.qingxuzhishu] / base) * base;
				}
				if(!site_MIN_zs || d[main_sz_title] < site_MIN_zs) {
					site_MIN_zs = Math.floor(d[main_sz_title] / base) * base;
				} else if(!site_MAX_zs || d[main_sz_title] > site_MAX_zs){
					site_MAX_zs = Math.ceil(d[main_sz_title] / base) * base;
				}
			});
			
			drawSite(indecatorName, echelonNames);
			drawIndicators(indecatorName, echelonNames);
			Configure.getMode() == Configure.modeType.DP  ?  
							drawBandEchelon(echelonNames) : drawZTEchelon(echelonNames);
			
			var emotionPoints = getLastEmotionPoints(Configure.Days_Max_lengh);    
			findTurnintPoint(emotionPoints, Configure.EmotionAngleDeafultDays + 1);
			drawEmotionTurning();
			window.performance.mark("Canvas:drawDone");
			Configure.Debug('Canvas draw duration:' 
				+ window.performance.measure("Canvas", "Canvas:draw", "Canvas:drawDone").duration + 'ms');
		}
	}
	
	return {
		init: init,
		resize:resize,
		reload:reload,
		draw: draw,
		drawEmotionCycle:drawEmotionCycle,
		drawEmotionTurning:drawEmotionTurning,
		sumAngleFromPoints:sumAngleFromPoints,
		sumValueFromPoints:sumValueFromPoints,
		getLastEmotionPoints:getLastEmotionPoints,
		getLastZBPoints:getLastZBPoints
	}
})();
